# Generated by Django 4.1.5 on 2023-02-17 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0013_alter_place_point2_alter_route_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 17, 12, 59, 32, 176141))),
                ('places', models.CharField(default='', max_length=4095)),
                ('distanceM', models.IntegerField(default=0)),
                ('timeM', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
