# Generated by Django 4.1.5 on 2023-02-17 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_historyroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyroute',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='userId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 20, 43, 46, 271620)),
        ),
    ]
