# Generated by Django 4.1.5 on 2023-02-19 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_rename_userid_historyroute_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('places', models.CharField(default='', max_length=4095)),
                ('distanceM', models.IntegerField(default=0)),
                ('timeM', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='isStatic',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 17, 43, 216750)),
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 17, 43, 217746)),
        ),
    ]
