# Generated by Django 4.1.5 on 2023-02-19 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_staticroute_remove_route_isstatic_remove_route_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 28, 21, 687758)),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 28, 21, 687758)),
        ),
    ]
