# Generated by Django 4.1.5 on 2023-02-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_alter_historyroute_date_alter_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 29, 46, 423105)),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 29, 46, 422069)),
        ),
    ]
