# Generated by Django 4.1.5 on 2023-02-19 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_alter_historyroute_date_alter_route_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyroute',
            name='countPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='countPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staticroute',
            name='countPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 34, 56, 660149)),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 34, 56, 658156)),
        ),
    ]
