# Generated by Django 4.1.5 on 2023-02-19 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_historyroute_countpoints_route_countpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 58, 8, 153077)),
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='distanceM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='timeM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 15, 58, 8, 152081)),
        ),
        migrations.AlterField(
            model_name='route',
            name='distanceM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='timeM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='distanceM',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='timeM',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
