# Generated by Django 4.1.5 on 2023-02-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_rename_distancem_historyroute_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 17, 38, 7, 260573, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 17, 38, 7, 258529, tzinfo=datetime.timezone.utc)),
        ),
    ]
