# Generated by Django 4.1.5 on 2023-02-19 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_alter_historyroute_date_alter_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyroute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 17, 39, 20, 66352, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historyroute',
            name='places',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 17, 39, 20, 65268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='route',
            name='places',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='places',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
